#!/usr/bin/env bash
set -uo pipefail

# Global vars to be used
# shellcheck source=stop
source "$(dirname "${BASH_SOURCE[0]}")"/stop

JAEGER_IMG="cr.jaegertracing.io/jaegertracing/jaeger:2.11.0"

echo "Starting $JAEGER_CTR"
"$CONTAINER_RUNTIME" run -d --rm --network host --name "$JAEGER_CTR" "$JAEGER_IMG"

PORT=14250
MAX_CNT=100
for ((i = 0; i <= "$MAX_CNT"; i++)); do
    if netstat -tuplen 2>/dev/null | grep -q "$PORT .* LISTEN"; then
        break
    fi

    if [[ $i == "$MAX_CNT" ]]; then
        echo "Giving up"
        exit 1
    fi

    echo "Waiting for gRPC port $PORT to listen… ($i)"
    sleep 3
done

echo "Everything is ready"
