#!/usr/bin/env bash
set -uo pipefail

# Global vars to be used
# shellcheck source=env
source "$(dirname "${BASH_SOURCE[0]}")"/env

echo "Stopping $JAEGER_CTR container"
"$CONTAINER_RUNTIME" stop "$JAEGER_CTR" >/dev/null 2>&1 || true
