#!/usr/bin/env bash
set -euo pipefail

# update the latest version marker file for the branch
MARKER=$(git rev-parse --abbrev-ref HEAD)
VERSION=$(git rev-parse HEAD)

# if in detached head state, we assume we're on a tag
if [[ $MARKER == HEAD ]]; then
    # use the major.minor as marker
    VERSION=$(git describe --tags --exact-match)
    MARKER=$(echo "$VERSION" | cut -c 2-5)
fi
echo "$VERSION" >"latest-$MARKER.txt"
