version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    labels:
      - "release-note-none"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      capnp:
        patterns:
          - "capnp*"
      opentelemetry:
        patterns:
          - "opentelemetry*"
          - "tracing-opentelemetry"
      rust-dependencies:
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "release-note-none"
