#!/usr/bin/env bash
set -euo pipefail

main() {
    set -x

    install_packages
    install_runc
}

install_packages() {
    sudo apt-get update
    sudo apt-get install -y capnproto
}

install_runc() {
    RUNC_VERSION=v1.1.3
    RUNTIME_PATH=/usr/sbin/runc

    sudo curl -sSfL --retry 5 --retry-delay 3 -o $RUNTIME_PATH \
        https://github.com/opencontainers/runc/releases/download/$RUNC_VERSION/runc.amd64
    sudo chmod +x $RUNTIME_PATH
    sudo $RUNTIME_PATH --version
}

main "$@"
